name: Build and Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Push page branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout --orphan pages
          git --work-tree pages add --all
          git commit -m "Build from commit $GITHUB_SHA"
          git push -f origin pages
