name: Build and Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git checkout --orphan pages
          rm -rf .github .gitignore node_modules src public package.json package-lock.json
          mv dist/* .
          git add .
          git commit -m "Deploy from commit $GITHUB_SHA"
          git push -f origin pages
